In [2]:
import random
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
from sklearn.metrics import classification_report
import graphviz
from sklearn.ensemble import RandomForestRegressor



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
wpt = nltk.WordPunctTokenizer()
stop_words = nltk.corpus.stopwords.words('english')

In [4]:
class LemmaTokenizer(object):
	def __init__(self):
		self.wnl = nltk.stem.WordNetLemmatizer()
	def __call__(self, doc):
		return [self.wnl.lemmatize(t) for t in nltk.word_tokenize(doc)]


In [5]:
df = pd.read_csv('C:/Users/Windows/Desktop/NUS/Pyhton/Main.csv',encoding='latin1',keep_default_na=False);
df = df[1:500];

dfx = df['tweet'];
dfy = df['class'];


In [6]:
x_train, x_test, y_train, y_test = train_test_split(dfx, dfy, train_size = 0.8, test_size = 0.2, random_state = random.randrange(99999), shuffle = True)

cv = CountVectorizer(tokenizer=LemmaTokenizer(), stop_words=stop_words, binary=True)
cv_matrix_train = cv.fit_transform(x_train)
vocab = cv.get_feature_names()
cv_matrix_train = cv_matrix_train.toarray()
cv_matrix_test =  cv.transform(x_test)
clf = LinearSVC();
clf.fit(cv_matrix_train, y_train);
y_pred_train = clf.predict(cv_matrix_train)
y_pred_test = clf.predict(cv_matrix_test)
print('Training Accuracy {}'.format(clf.score(cv_matrix_train, y_train)))
print('Training Confusion = {}'.format(metrics.confusion_matrix(y_pred_train, y_train)))
print(classification_report(y_train, y_pred_train))
print('========================================================')
print('Test Accuracy {}'.format(clf.score(cv_matrix_test, y_test)))
print('Test Confusion = {}'.format(metrics.confusion_matrix(y_pred_test, y_test)))
print(classification_report(y_test, y_pred_test))


Training Accuracy 1.0
Training Confusion = [[ 12   0   0]
 [  0 336   0]
 [  0   0  51]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       1.00      1.00      1.00       336
          2       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       399

Test Accuracy 0.94
Test Confusion = [[ 0  0  0]
 [ 2 84  3]
 [ 0  1 10]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         2
          1       0.94      0.99      0.97        85
          2       0.91      0.77      0.83        13

avg / total       0.92      0.94      0.93       100



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
